import { ICountry } from '../interfaces/ICountry';
import { IRegion } from '../interfaces/IRegion';

export const defaultCountry: ICountry = {
	alpha2Code: 'US',
	alpha3Code: 'USA',
	altSpellings: ['US', 'USA', 'United States of America'],
	area: 9629091,
	borders: ['CAN', 'MEX'],
	callingCodes: ['1'],
	capital: 'Washington, D.C.',
	cioc: 'USA',
	currencies: [{ code: 'USD', name: 'United States dollar', symbol: '$' }],
	demonym: 'American',
	flag: 'https://restcountries.eu/data/usa.svg',
	gini: 48,
	languages: [
		{
			iso639_1: 'en',
			iso639_2: 'eng',
			name: 'English',
			nativeName: 'English',
		},
	],

	latlng: [38, -97],
	name: 'United States of America',
	nativeName: 'United States',
	numericCode: '840',
	population: 323947000,
	region: 'Americas',
	regionalBlocs: [
		{
			acronym: 'NAFTA',
			name: 'North American Free Trade Agreement',
			otherAcronyms: [],
			otherNames: [
				'Tratado de Libre Comercio de América del Norte',
				'Accord de Libre-échange Nord-Américain',
			],
		},
	],
	subregion: 'Northern America',
	timezones: [
		'UTC-12:00',
		'UTC-11:00',
		'UTC-10:00',
		'UTC-09:00',
		'UTC-08:00',
		'UTC-07:00',
		'UTC-06:00',
		'UTC-05:00',
		'UTC-04:00',
		'UTC+10:00',
		'UTC+12:00',
	],
	topLevelDomain: ['.us'],
	translations: {
		br: 'Estados Unidos',
		de: 'Vereinigte Staaten von Amerika',
		es: 'Estados Unidos',
		fa: 'ایالات متحده آمریکا',
		fr: 'États-Unis',
		hr: 'Sjedinjene Američke Države',
		it: "Stati Uniti D'America",
		ja: 'アメリカ合衆国',
		nl: 'Verenigde Staten',
	},
};

export const defaultRegions: IRegion[] = [
	{
		countryCode: 'US',
		fipsCode: '01',
		isoCode: 'AL',
		name: 'Alabama',
		wikiDataId: 'Q173',
	},
	{
		countryCode: 'US',
		fipsCode: '02',
		isoCode: 'AK',
		name: 'Alaska',
		wikiDataId: 'Q797',
	},
	{
		countryCode: 'US',
		fipsCode: 'AQ',
		isoCode: 'AS',
		name: 'American Samoa',
		wikiDataId: 'Q16641',
	},
	{
		countryCode: 'US',
		fipsCode: '04',
		isoCode: 'AZ',
		name: 'Arizona',
		wikiDataId: 'Q816',
	},
	{
		countryCode: 'US',
		fipsCode: '05',
		isoCode: 'AR',
		name: 'Arkansas',
		wikiDataId: 'Q1612',
	},
	{
		countryCode: 'US',
		fipsCode: '06',
		isoCode: 'CA',
		name: 'California',
		wikiDataId: 'Q99',
	},
	{
		countryCode: 'US',
		fipsCode: '08',
		isoCode: 'CO',
		name: 'Colorado',
		wikiDataId: 'Q1261',
	},
	{
		countryCode: 'US',
		fipsCode: '09',
		isoCode: 'CT',
		name: 'Connecticut',
		wikiDataId: 'Q779',
	},
	{
		countryCode: 'US',
		fipsCode: '10',
		isoCode: 'DE',
		name: 'Delaware',
		wikiDataId: 'Q1393',
	},
	{
		countryCode: 'US',
		fipsCode: '11',
		isoCode: 'DC',
		name: 'District of Columbia',
		wikiDataId: 'Q3551781',
	},
];
